### ISSUE TITLE
Error after upgrade from 0.8.1 to 0.10.4

### ISSUE THREAD

**Issue by ulou** [dougludlow/ng2-bs3-modal#119]
After updating ng2-bs3-modal from 0.8.1 to 0.10.4  and angular2 from rc6 to final 2.0.0, following errors occurs:
```
  C:/Users/frontend/tmp/broccoli_type_script_compiler-input_base_path-nrj9TPsx.tmp/0/src/app/dashboard/agent/agent.component.ts (46, 27): Property 'close' does not exist on type 'ModalComponent'.
  C:/Users/frontend/tmp/broccoli_type_script_compiler-input_base_path-nrj9TPsx.tmp/0/src/app/dashboard/agent/agent.component.ts (55, 27): Property 'open' does not exist on type 'ModalComponent'.
  C:/Users/frontend/tmp/broccoli_type_script_compiler-input_base_path-nrj9TPsx.tmp/0/src/app/dashboard/agent/agent.component.ts (62, 21): Property 'close' does not exist on type 'ModalComponent'.
  C:/Users/frontend/tmp/broccoli_type_script_compiler-input_base_path-nrj9TPsx.tmp/0/src/app/dashboard/agent/agent.component.ts (67, 21): Property 'close' does not exist on type 'ModalComponent'.
```
Following code:

```  
...
@ViewChild('agentModal')
  agentModal: ModalComponent;
  closeAgent() {
    this.agentModal.close();
  }

  openAgent(id: number) {
    this.openedAgentId = id;
    this.agentModal.close();
  }
...
```

any ideas?

**Comment by dougludlow** [comment]
@ulou are you using typescript v2?

**Comment by ulou** [comment]
@dougludlow  
`"typescript": "2.0.2",`

**Comment by prasadrajacse** [comment]
I am also getting the same error.

**Comment by dougludlow** [comment]
@ulou, @prasadrajacse - where are you seeing this error? during compilation? what editor are you using?

**Comment by prasadrajacse** [comment]
@dougludlow  I tried with both webstorm and sublime.

**Comment by prasadrajacse** [comment]
@ViewChild('modal') private modal: ElementRef;
  modal: ModalComponent;
close() {
   // this.modal.close();
    this.modal.nativeElement.close();
  }

This is also failing.

**Comment by dougludlow** [comment]
@ulou, @prasadrajacse - `ng2-bs3-modal` requires typescript 2. But the editor's typescript version can be different from the projects version, which was the case in #113.

**Comment by prasadrajacse** [comment]
@dougludlow. My project typescript version is 2.0.3. In webstorm pointing to local typescript lib is also throwing the same error. Now the project is compiled successfully but this error msg is seen at run time. "EXCEPTION: Cannot read property 'open' of undefined"

**Comment by dougludlow** [comment]
@prasadrajacse when are you calling open? it's possible that it's being called before the modal has been bound to the `modal` property.

**Comment by prasadrajacse** [comment]
I am calling it in ngOnInit(). Is there anyway to bind the default properties/methods to modal before any function call ?

**Comment by dougludlow** [comment]
@prasadrajacse - no, `ngOnInit` happens before the view has been initiated. You'll need to use `ngAfterViewInit`.  See [Lifecyle Hooks](https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html) for more details.

**Comment by prasadrajacse** [comment]
@dougludlow I tried that before as well...this.modal is shown as undefined. Do you have any other idea ?

**Comment by dougludlow** [comment]
@prasadrajacse the `modal` property isn't set until AfterViewInit. See the [ViewChild decorator documentation](https://angular.io/docs/ts/latest/api/core/index/ViewChild-decorator.html). 

I don't have enough information about your project's configuration to provide much more help. Code snippets or a demo would be very useful.

**Comment by prasadrajacse** [comment]
@dougludlow.... Thanks for the support, I understand that my project configs needs to be changed here.I created sample app and it is working fine. If @ulou is fine you can close the ticket.I really appreciate your quality time in coming up with wonderful component, it really saves a lot of development effect. Cheers.

**Comment by dougludlow** [comment]
@prasadrajacse I looking at the code you posted above, it looks like you have declared the `modal` property twice, which might be problematic:

```
@ViewChild('modal') private modal: ElementRef;
modal: ModalComponent;
```

Instead, this should simply be:

```
@ViewChild('modal') private modal: ModalComponent;
```

**Comment by dougludlow** [comment]
@ulou i'm guessing this is an issue with your editor's typescript version being out of sync with your projects. Any detail you can provide would be great.

**Comment by dougludlow** [comment]
@ulou - closing for now, feel free to reopen if you're still experiencing issues.

**Comment by dbohl** [comment]
I just started using this, but I'm having this same issue.  I tried v0.8.1 as the original posted mentioned, and verified that makes the problem go away.

I'm using WebStorm and typescript 2.0.3.  WebStorm is configured to use settings from tsconfig.json, whose target is "es6".

I'm currently using this as a work-around:
`this.agentModal["close"]();`
