### PR TITLE
update to Angular 2.0.0

### PR DESCRIPTION
**Pull request by jbrekle**
nothing special. 

But I had to downgrade the  typescript compiler because 2.0.0 gave me 

```
$ tsc --project . --declaration --outDir ./
   error TS5009: Cannot find the common subdirectory path for the input files.
```

on my Win7 machine with node v6.5.0

### CODE REVIEW

**Comment by damiandennis** [comment]
oops did not see this one :D

**Comment by damiandennis** [comment]
I think Angular2 is only supporting up to node 5.x.x as mentioned on their quickstart guide so you might want to downgrade and try again.

**Comment by jbrekle** [comment]
quickstart says  "v5.x.x or higher". not "up to". And I can't get it to compile with 5.9.1

**Comment by jbrekle** [comment]
But I don't really care if this builds on my machine, just take #108 then
