### PR TITLE
updated to beta 14

### PR DESCRIPTION
**Pull request by samvloeberghs**
there is also something wrong with the Typings after updating to 0.5

### CODE REVIEW

**Comment by dougludlow** [comment]
@samvloeberghs are you getting any particular error message?

**Comment by samvloeberghs** [comment]
@dougludlow 
I'm using https://github.com/AngularClass/angular2-webpack-starter as the baseproject
I get this after updating to 0.5.0:

```
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (4,22):
    Class 'ModalComponent' incorrectly implements interface 'CanDeactivate'.
  Property 'routerCanDeactivate' is missing in type 'ModalComponent'.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (4,22):
    Class 'ModalComponent' incorrectly implements interface 'OnDestroy'.
  Property 'ngOnDestroy' is missing in type 'ModalComponent'.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (16,5):
    Duplicate identifier 'readonly'.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (16,14):
    '=' expected.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (16,14):
    Cannot find name 'fadeClass'.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (16,23):
    ';' expected.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (16,25):
    Duplicate identifier 'boolean'.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (17,5):
    Duplicate identifier 'readonly'.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (17,14):
    '=' expected.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (17,14):
    Cannot find name 'dataKeyboardAttr'.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (17,30):
    ';' expected.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (17,32):
    Duplicate identifier 'boolean'.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (18,5):
    Duplicate identifier 'readonly'.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (18,14):
    '=' expected.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (18,14):
    Cannot find name 'dataBackdropAttr'.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (18,30):
    ';' expected.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (18,32):
    Unexpected token. A constructor, method, accessor, or property was expected.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (18,32):
    Cannot find name 'string'.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (18,41):
    Cannot find name 'boolean'.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (19,5):
    Cannot find name 'constructor'.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (19,17):
    Cannot find name 'element'.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (19,24):
    ',' expected.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (20,5):
    Cannot find name 'ngOnDestroy'.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (20,18):
    ';' expected.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (20,20):
    Value of type 'PromiseConstructor' is not callable. Did you mean to include 'new'?
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (20,32):
    '(' expected.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (21,5):
    Cannot find name 'routerCanDeactivate'.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (21,26):
    ';' expected.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (21,28):
    Cannot find name 'any'.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (22,10):
    Cannot find name 'size'.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (22,15):
    Expression expected.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (22,17):
    Cannot find name 'string'.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (22,24):
    ';' expected.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (22,26):
    Value of type 'PromiseConstructor' is not callable. Did you mean to include 'new'?
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (22,39):
    '(' expected.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (23,12):
    ';' expected.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (23,14):
    Value of type 'PromiseConstructor' is not callable. Did you mean to include 'new'?
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (23,27):
    '(' expected.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (24,5):
    Cannot find name 'dismiss'.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (24,14):
    ';' expected.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (24,16):
    Value of type 'PromiseConstructor' is not callable. Did you mean to include 'new'?
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (24,29):
    '(' expected.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (25,5):
    Declaration or statement expected.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (25,13):
    Cannot find name 'isSmall'.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (26,5):
    Declaration or statement expected.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (26,13):
    Cannot find name 'isLarge'.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/node_modules/ng2-bs3-modal/components/modal.d.ts (27,1):
    Declaration or statement expected.
[default] /Volumes/Data/Kwerri/projecten/immoweb/coresitev2.0_angular2/src/common/components/iw-modal/iwModal.ts (52,16):
    Property 'open' does not exist on type 'ModalComponent'.
```

**Comment by dougludlow** [comment]
Ah, I see what might be going on here. What version of typescript do you use?

**Comment by samvloeberghs** [comment]
```
Sams-MacBook-Pro: samvloeberghs$ tsc -v
Version 1.8.7

```

**Comment by dougludlow** [comment]
Yeah... I probably need to downgrade the project's version of typescript. I've been using typescript@next which resolves to some version of 1.9. Sorry about that.

**Comment by samvloeberghs** [comment]
You can merge this PR tough :)
It only updates for beta 14

**Comment by dougludlow** [comment]
Merged, thanks.

Also v0.5.1 should resolve the typing issues.
